name: Python Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov flake8
      - name: Install Playwright
        run: |
          playwright install chromium
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Create example config files for testing
        run: |
          cp .env.example .env.test
          cp airtable_config.example.json airtable_config.test.json
          # Add test values to .env.test
          echo "OPENAI_API_KEY=sk-test-key" >> .env.test
          echo "TAVILY_API_KEY=test-key" >> .env.test
      - name: Test with pytest
        run: |
          pytest --cov=./ --cov-report=xml
        env:
          # Use test environment variables
          OPENAI_API_KEY: sk-test-key
          TAVILY_API_KEY: test-key
          FIRECRAWL_API_KEY: test-key
          AIRTABLE_API_KEY: test-key
          # Disable actual API calls during tests
          TESTING: true
